version: '3'
services:
    db:
        image: "postgres:9.5"
        ports:
            - "5432:5432"
        volumes:
            - ./pgdata:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=password
    zookeeper-server:
        image: 'bitnami/zookeeper:latest'
        ports:
            - '2181:2181'
        environment:
            - ALLOW_ANONYMOUS_LOGIN=yes
    kafka-server:
        image: 'bitnami/kafka:latest'
        ports:
            - '9092:9092'
        environment:
            - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-server:2181
            - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
            - ALLOW_PLAINTEXT_LISTENER=yes
        depends_on:
            - zookeeper-server
    statsd-server:
        image: "graphiteapp/graphite-statsd"
        ports:
            - "80:80"
            - "2003-2004:2003-2004"
            - "2023-2024:2023-2024"
            - "8125:8125/udp"
            - "8126:8126"
    app:
        build: .
        ports:
            - "5000:5000"