version: '3'
networks:
    kafka-net:
        driver: bridge

services:
    db:
        image: "postgres:9.5"
        ports:
            - "5432:5432"
        volumes:
            - ./pgdata:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=password
    zookeeper:
        image: 'bitnami/zookeeper:latest'
        networks:
            - kafka-net
        ports:
            - '2181:2181'
        environment:
            - ALLOW_ANONYMOUS_LOGIN=yes
    kafka:
        image: 'bitnami/kafka:latest'
        networks:
            - kafka-net
        ports:
            - '9092:9092'
            - '9093:9093'
        environment:
            - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
            - ALLOW_PLAINTEXT_LISTENER=yes
            - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
            - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
            - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
            - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
        depends_on:
            - zookeeper
    statsd:
        image: "graphiteapp/graphite-statsd"
        ports:
            - "80:80"
            - "2003-2004:2003-2004"
            - "2023-2024:2023-2024"
            - "8125:8125/udp"
            - "8126:8126"
    app:
        build: .
        networks:
            - kafka-net
        ports:
            - "5000:5000"
        environment:
            - KAFKA_SEED_BROKERS=kafka://kafka:9092
            - KAFKA_CLIENT_ID=example_app