development: 
  host: <%= ENV['HOST'] %>
  twilio_account_sid: <%= ENV["TWILIO_ACCOUNT_SID"] %>
  twilio_auth_token: <%= ENV["TWILIO_AUTH_TOKEN"] %>
  twilio_sender: <%= ENV["TWILIO_SENDER"] %>
  twilio_telehealth: <%= ENV["TWILIO_TELEHEALTH"] %>
  twilio_status_callback: <%= ENV["TWILIO_STATUS_CALLBACK"] %>
  twilio_sandbox_receiver: <%= ENV["TWILIO_SANBOX_RECEIVER"] %>

test:
  host: 'http://localhost'

production:
  host: <%= ENV['HOST'] %>
  twilio_account_sid: <%= ENV["TWILIO_ACCOUNT_SID"] %>
  twilio_auth_token: <%= ENV["TWILIO_AUTH_TOKEN"] %>
  twilio_sender: <%= ENV["TWILIO_SENDER"] %>
  twilio_telehealth: <%= ENV["TWILIO_TELEHEALTH"] %>
  twilio_status_callback: <%= ENV["TWILIO_STATUS_CALLBACK"] %>